### ISSUE TITLE
NullPointerException during justification analysis under presence of negative integer terms

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#158]
`NullPointerException` during justification analysis under presence of negative integer terms.

Stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at at.ac.tuwien.kr.alpha.common.terms.ArithmeticTerm.normalizeVariables(ArithmeticTerm.java:57)
	at at.ac.tuwien.kr.alpha.common.terms.Term.renameTerms(Term.java:85)
	at at.ac.tuwien.kr.alpha.common.atoms.BasicAtom.normalizeVariables(BasicAtom.java:99)
	at at.ac.tuwien.kr.alpha.common.atoms.BasicAtom.normalizeVariables(BasicAtom.java:1)
	at at.ac.tuwien.kr.alpha.grounder.structure.LitSet.computeNormalized(LitSet.java:123)
	at at.ac.tuwien.kr.alpha.grounder.structure.LitSet.computeNormalizedSubstitutions(LitSet.java:136)
	at at.ac.tuwien.kr.alpha.grounder.structure.LitSet.<init>(LitSet.java:40)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.unjustCover(AnalyzeUnjustified.java:239)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.unjustCover(AnalyzeUnjustified.java:248)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.explainUnjust(AnalyzeUnjustified.java:166)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.analyze(AnalyzeUnjustified.java:69)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.analyze(AnalyzeUnjustified.java:54)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.justifyAtom(NaiveGrounder.java:578)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.justifyMbtAndBacktrack(DefaultSolver.java:285)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:194)
	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:34)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at at.ac.tuwien.kr.alpha.Main.computeAndConsumeAnswerSets(Main.java:281)
	at at.ac.tuwien.kr.alpha.Main.main(Main.java:264)
```

Can be reproduced with the KnightTourWithHoles problem.

Encoding: `encoding.asp` from [ASP Competition 2015](http://aspcomp2015.dibris.unige.it/KnightTourWithHoles.zip)

Instance: Example from [ASP Competition 2013](https://www.mat.unical.it/aspcomp2013/KnightTour):
```
size(9).
forbidden(1,9). forbidden(2,9). forbidden(3,9). forbidden(4,9). forbidden(5,9). forbidden(6,9). forbidden(7,9). forbidden(8,9). forbidden(9,9).
forbidden(9,1). forbidden(9,2). forbidden(9,3). forbidden(9,4). forbidden(9,5). forbidden(9,6). forbidden(9,7). forbidden(9,8). forbidden(9,9).
```

**Comment by rtaupe** [comment]
Fixed by d2e7a72fbbb175c6ef01084053d6300a5131c4ce. However, the same problem raises another issue: #159
