### ISSUE TITLE
Program unsatisfiable because arithmetic terms are not evaluated

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#159]
A program that is actually satisfiable is reported to be unsatisfiable, apparently because arithmetic terms are not evaluated in time.

Can be reproduced with the KnightTourWithHoles problem.

Encoding: `encoding.asp` from [ASP Competition 2015](http://aspcomp2015.dibris.unige.it/KnightTourWithHoles.zip)

Instance: Example from [ASP Competition 2013](https://www.mat.unical.it/aspcomp2013/KnightTour):
```
size(9).
forbidden(1,9). forbidden(2,9). forbidden(3,9). forbidden(4,9). forbidden(5,9). forbidden(6,9). forbidden(7,9). forbidden(8,9). forbidden(9,9).
forbidden(9,1). forbidden(9,2). forbidden(9,3). forbidden(9,4). forbidden(9,5). forbidden(9,6). forbidden(9,7). forbidden(9,8). forbidden(9,9).
```

**Comment by rtaupe** [comment]
PRs #160 and #161 contribute to a fix for this issue, but are apparently not enough, Alpha still returns UNSATISFIABLE.

Maybe the following issue is related:

In a rewriting of KnightTourWithHoles (see [KnightTourWithHoles_rewriting.txt](https://github.com/alpha-asp/Alpha/files/2792340/KnightTourWithHoles_rewriting.txt) for program and example instance), Alpha raises the following Exception:
```
Exception in thread "main" java.lang.NullPointerException
        at at.ac.tuwien.kr.alpha.common.AtomStoreImpl.get(AtomStoreImpl.java:161)
        at at.ac.tuwien.kr.alpha.solver.DefaultSolver.noGoodFromJustificationReasons(DefaultSolver.java:307)
        at at.ac.tuwien.kr.alpha.solver.DefaultSolver.justifyMbtAndBacktrack(DefaultSolver.java:286)
        at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:194)
        at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:34)
        at java.util.Spliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at at.ac.tuwien.kr.alpha.Main.computeAndConsumeAnswerSets(Main.java:281)
        at at.ac.tuwien.kr.alpha.Main.main(Main.java:264)
```
The cause for the exception is that `AtomStoreImpl.get(Atom)` is asked to look up `forbidden(1, 9)` by `DefaultSolver.noGoodFromJustificationReasons(int, Set<Literal>)`. The atom `forbidden(1, 9)`, however, is a fact.
