### ISSUE TITLE
Bug: No rule grounding order for constraints with anonymous variables

### ISSUE THREAD

**Issue by madmike200590** [alpha-asp/Alpha#194]
The following code (also attached) gives the attached 27 answer sets executed with "clingo -n 0 <infile>":
```
a(1..3).
b(1..3).

{c(X, Y) : b(Y)} :- a(X).

:- a(X), not c(X, _).
:- a(X), c(X, Y1), c(X, Y2), Y1 != Y2.
```

Alpha gets an error with the same input:
```
Exception in thread "main" java.lang.RuntimeException: Could not find a grounding order for rule :- a(X), not c(X, _0). with starting literal: a(X). Rule is not safe.
	at at.ac.tuwien.kr.alpha.grounder.RuleGroundingOrder.computeGroundingOrder(RuleGroundingOrder.java:175)
	at at.ac.tuwien.kr.alpha.grounder.RuleGroundingOrder.computeGroundingOrders(RuleGroundingOrder.java:155)
	at at.ac.tuwien.kr.alpha.grounder.NonGroundRule.<init>(NonGroundRule.java:75)
	at at.ac.tuwien.kr.alpha.grounder.NonGroundRule.constructNonGroundRule(NonGroundRule.java:94)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.initializeFactsAndRules(NaiveGrounder.java:141)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.<init>(NaiveGrounder.java:107)
	at at.ac.tuwien.kr.alpha.grounder.GrounderFactory.getInstance(GrounderFactory.java:40)
	at at.ac.tuwien.kr.alpha.grounder.GrounderFactory.getInstance(GrounderFactory.java:46)
	at at.ac.tuwien.kr.alpha.Alpha.prepareSolverFor(Alpha.java:123)
	at at.ac.tuwien.kr.alpha.Main.computeAndConsumeAnswerSets(Main.java:88)
	at at.ac.tuwien.kr.alpha.Main.main(Main.java:84)
```

The problem seems to be that no RuleGroundingOrder can be computed due to the anonymous variable in the first constraint.

[test_constraints1_alpha.asp.txt](https://github.com/alpha-asp/Alpha/files/3389222/test_constraints1_alpha.asp.txt)
[answer_sets_clingo.txt](https://github.com/alpha-asp/Alpha/files/3389223/answer_sets_clingo.txt)

**Comment by madmike200590** [comment]
Not sure if that closely related, but it seems to make sense to also take care of issue #154 while fixing this

**Comment by AntoniusW** [comment]
Actually, Alpha's behavior is correct. The first constraint is not safe, because the anonymous variable occurs in a negated literal and hence cannot be bound by the positive body.

Clingo, on the other hand, decided that it is useful to allow anonymous variables in negated literals to express that "there exists no c(X, Y) for any Y" in a very concise form. The correct way of expressing this would require a new rule `cc(X) :- c(X,_).` and the constraint to read `:- a(X), not cc(X).`

Since this feature of Clingo is very useful, we should seriously consider adding it to Alpha. The current behavior, however is actually correct.
