### ISSUE TITLE
NullPointerException when trying arithmetics with non-numeric term

### ISSUE THREAD

**Issue by madmike200590** [alpha-asp/Alpha#203]
The following snippet (also attached) 
[npe_arithmetics.txt](https://github.com/alpha-asp/Alpha/files/3720534/npe_arithmetics.txt)

produces a NullPointerException:
```
add(1, 2).
add(nonsense, 3).

num(X) :- add(Y, Z), X = Y + Z.
```
StackTrace is:
```
Exception in thread "main" java.lang.NullPointerException
	at at.ac.tuwien.kr.alpha.common.terms.ConstantTerm.hashCode(ConstantTerm.java:77)
	at java.base/java.util.WeakHashMap.hash(WeakHashMap.java:298)
	at java.base/java.util.WeakHashMap.get(WeakHashMap.java:397)
	at at.ac.tuwien.kr.alpha.common.Interner.intern(Interner.java:15)
	at at.ac.tuwien.kr.alpha.common.terms.ConstantTerm.getInstance(ConstantTerm.java:25)
	at at.ac.tuwien.kr.alpha.common.terms.ArithmeticTerm.getInstance(ArithmeticTerm.java:58)
	at at.ac.tuwien.kr.alpha.common.terms.ArithmeticTerm.substitute(ArithmeticTerm.java:78)
	at at.ac.tuwien.kr.alpha.common.atoms.ComparisonAtom.lambda$substitute$0(ComparisonAtom.java:74)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at at.ac.tuwien.kr.alpha.common.atoms.ComparisonAtom.substitute(ComparisonAtom.java:74)
	at at.ac.tuwien.kr.alpha.common.atoms.ComparisonLiteral.substitute(ComparisonLiteral.java:76)
	at at.ac.tuwien.kr.alpha.common.atoms.ComparisonLiteral.substitute(ComparisonLiteral.java:44)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.bindNextAtomInRule(NaiveGrounder.java:420)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.getNoGoods(NaiveGrounder.java:351)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:113)
	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:34)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at at.ac.tuwien.kr.alpha.Main.computeAndConsumeAnswerSets(Main.java:101)
	at at.ac.tuwien.kr.alpha.Main.main(Main.java:84)
```
The problem seems to be that Alpha tries to perform the addition ```Y + Z``` with substitution ```Y -> nonsense, Z -> 3```, which doesn't work.

According to the ASP Core2 standard "_A global substitution σ for [a rule] r (or substitution σ for e) is well-formed if the arithmetic evaluation, performed in the standard way, of any arithmetic subterm (−(t) or (t OP u) with OP ∈ {“+”, “−”,
“∗”, “/”}) appearing outside of aggregate elements in rσ (or appearing in eσ) is well-defined_".
So, according to the standard, the ground substitution causing above issue should never be yielded by bindNextAtom in the first place.

**Comment by madmike200590** [comment]
This should probably be  taken care of as part of implementing #89
