### ISSUE TITLE
Justification analysis fails on external atoms on branch stdlib_externals

### ISSUE THREAD

**Issue by madmike200590** [alpha-asp/Alpha#229]
Following code on branch stdlib_externals leads to an exception when solving:
```
string("bla").
string("blubb").
string("foo").
string("bar").
{ strcat(S1, S2) } :- string(S1), string(S2).
resultstring(SCAT) :- strcat(S1, S2), &stdlib_string_concat[S1, S2](SCAT).
:- resultstring(S), &stdlib_string_length[S](LEN), LEN != 6.
containsFoo(S) :- resultstring(S), &stdlib_string_matches_regex[S, ".*foo.*"].
:- resultstring(S), not containsFoo(S).
```
The exception thrown by the solver is:
```
java.lang.RuntimeException: Atom to normalize is of unknown type: &stdlib_string_matches_regex["barbar", ".*foo.*"]! Should not happen.
	at at.ac.tuwien.kr.alpha.Util.oops(Util.java:96)
	at at.ac.tuwien.kr.alpha.grounder.structure.LitSet.computeNormalized(LitSet.java:125)
	at at.ac.tuwien.kr.alpha.grounder.structure.LitSet.<init>(LitSet.java:39)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.unjustCover(AnalyzeUnjustified.java:239)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.unjustCover(AnalyzeUnjustified.java:248)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.explainUnjust(AnalyzeUnjustified.java:166)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.analyze(AnalyzeUnjustified.java:69)
	at at.ac.tuwien.kr.alpha.grounder.structure.AnalyzeUnjustified.analyze(AnalyzeUnjustified.java:54)
	at at.ac.tuwien.kr.alpha.grounder.NaiveGrounder.justifyAtom(NaiveGrounder.java:747)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.justifyMbtAndBacktrack(DefaultSolver.java:307)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:220)
	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:34)
```

**Comment by madmike200590** [comment]
Fixed in PR #228 , close when PR is merged
