### ISSUE TITLE
Lower bound cannot be given after the aggregate

### ISSUE THREAD

**Issue by rtaupe** [alpha-asp/Alpha#311]
Putting the lower bound of an aggregate _after_ an aggregate instead of _before_ it results in a `NullPointerException`.

For example, the following program:
```
p(1).
p(2).
q :- #count { N : p(N) } > 2.
```
results in:
```
Exception in thread "main" java.lang.NullPointerException
        at at.ac.tuwien.kr.alpha.grounder.transformation.aggregates.AggregateOperatorNormalization.rewriteAggregateOperator(AggregateOperatorNormalization.java:81)
        at at.ac.tuwien.kr.alpha.grounder.transformation.aggregates.AggregateOperatorNormalization.rewriteLiteral(AggregateOperatorNormalization.java:63)
        at at.ac.tuwien.kr.alpha.grounder.transformation.aggregates.AggregateOperatorNormalization.normalize(AggregateOperatorNormalization.java:56)
        at at.ac.tuwien.kr.alpha.grounder.transformation.aggregates.AggregateRewriting.apply(AggregateRewriting.java:77)
        at at.ac.tuwien.kr.alpha.grounder.transformation.NormalizeProgramTransformation.apply(NormalizeProgramTransformation.java:31)
        at at.ac.tuwien.kr.alpha.api.Alpha.normalizeProgram(Alpha.java:125)
        at at.ac.tuwien.kr.alpha.Main.main(Main.java:98)
```

Related to #268.

**Comment by madmike200590** [comment]
Thanks for catching this! I overlooked that scenario - for some reason I assumed there would always be a term and operator on the left of the aggregate.
I'll fix this as soon as I get to it, probably some time next week.
