### ISSUE TITLE
Exception when using '!='-operator

### ISSUE THREAD

**Issue by tobiaskaminski** [alpha-asp/Alpha#46]
When I call Alpha with the following program, an exception is returned:
```
location(a1).
region(r1).
region(r2).

assign(L,R) :- location(L), region(R), not nassign(L,R).
nassign(L,R) :- location(L), region(R), not assign(L,R).

:- assign(L,R1), assign(L,R2), R1 != R2.

aux_ext_assign(a1,r1).
aux_ext_assign(a1,r2).

aux_not_assign(L,R) :- aux_ext_assign(L,R), not assign(L,R).
:- aux_not_assign(L,R), assign(L,R).
```
The output is the following:
```
  209 I tuwien.kr.alpha.Main Seed for pseudorandomization is 6083566175591. 
Exception in thread "main" java.lang.IllegalArgumentException: Zero is not a literal (because it cannot be negated).
	at at.ac.tuwien.kr.alpha.common.Literals.atomOf(Literals.java:13)
	at at.ac.tuwien.kr.alpha.solver.GroundConflictNoGoodLearner.computeBackjumpingDecisionLevel(GroundConflictNoGoodLearner.java:250)
	at at.ac.tuwien.kr.alpha.solver.GroundConflictNoGoodLearner.analyzeConflictingNoGoodRepetition(GroundConflictNoGoodLearner.java:129)
	at at.ac.tuwien.kr.alpha.solver.GroundConflictNoGoodLearner.repeatAnalysisIfNotAssigning(GroundConflictNoGoodLearner.java:178)
	at at.ac.tuwien.kr.alpha.solver.GroundConflictNoGoodLearner.analyzeConflictingNoGoodRepetition(GroundConflictNoGoodLearner.java:134)
	at at.ac.tuwien.kr.alpha.solver.GroundConflictNoGoodLearner.analyzeConflictingNoGood(GroundConflictNoGoodLearner.java:76)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.addAllNoGoodsAndTreatContradictions(DefaultSolver.java:388)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.obtainNoGoodsFromGrounder(DefaultSolver.java:348)
	at at.ac.tuwien.kr.alpha.solver.DefaultSolver.tryAdvance(DefaultSolver.java:151)
	at at.ac.tuwien.kr.alpha.solver.AbstractSolver$1.tryAdvance(AbstractSolver.java:31)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at at.ac.tuwien.kr.alpha.Main.main(Main.java:224)
```
However, if I replace the operator '!=' by using 'unequal'-facts, the exception does not occur. Thus, the problem might be connected to #45. The translation, which does not yield the exception, is the following:
```
location(a1).
region(r1).
region(r2).

assign(L,R) :- location(L), region(R), not nassign(L,R).
nassign(L,R) :- location(L), region(R), not assign(L,R).

:- assign(L,R1), assign(L,R2), unequal(R1,R2).

aux_ext_assign(a1,r1).
aux_ext_assign(a1,r2).

aux_not_assign(L,R) :- aux_ext_assign(L,R), not assign(L,R).
:- aux_not_assign(L,R), assign(L,R).

unequal(r1,r2).
unequal(r2,r1).
```

**Comment by AntoniusW** [comment]
Since 67650da the above program now yields the expected answer sets.
